### ISSUE TITLE
Can't receive message after build

### ISSUE THREAD

**Issue by ankd-k** [Iam1337/extOSC#11]
In editor I can receive OSC message and use it by Reflection Component.
After build the app, It can't receive the message send from same app.
Sending app is work correctly, other OSC receiver app catch the message.
I run `netstat` and find that the built app using specified port. 

Do you have any idea to receive message after build?

**Comment by Iam1337** [comment]
Hi, if you are testing applications between different devices, then check if the firewall is turned off on both devices. If it does not help, write in more detail how you use extOSC.

**Comment by ankd-k** [comment]
I turned off the firewall when I opened the issue, but it didn't matter.

I don't understand the difference between the two receiver components, "event" and "reflection".
Replacing the component from "Reflection" to "Event" works fine.

The first question I asked (if you select the "Reflection" component, extOSC works in the editor, not after the build) will continue to occur.
What is the difference between the behavior of the "event" and "reflection" components after the build?

**Comment by Iam1337** [comment]
The Reflection component uses .NET Reflection to transmit data from messages. In some cases, this gives a greater number of available fields, methods, or properties.
Event component works using UnityEvent.

What settings do you use in "Reflection", "Event", OSCTransmitter and OSCReceiver components on both sides?

I will try to repeat your problem.

**Comment by ankd-k** [comment]
[This image](https://user-images.githubusercontent.com/38464796/76807387-1de16c00-67dc-11ea-9b0d-8afad3735bcd.jpg) is my extOSC component's inspector view.
Receiver components (`Reflection` and `Event`) activate only one side as you can see.
I don't edit other settings, probably it's almost defalut settings.

**Comment by Iam1337** [comment]
I found the problem. Thank you for contacting. You help make extOSC better.
