### ISSUE TITLE
Missing Window -> extOSC editor option

### ISSUE THREAD

**Issue by jlankitus** [Iam1337/extOSC#13]
![image](https://user-images.githubusercontent.com/10730933/97815686-bed64780-1c44-11eb-9840-e808283cc39f.png)

I have the FaceCap app for iOS, not getting any results with live mode. Using this github repo: https://github.com/hizzlehoff/FaceCapOSCReceiverExample

When trying to debug, I wanted to use the Window -> extOSC debug window, and noticed it is not present. I'm using Unity 2019.3.11, and package 1.19.5

**Comment by Iam1337** [comment]
Hi, in newer versions of extOSC: "Window -> extOSC -> OSC Debug" moved to "Tools -> extOSC -> OSC Debug".
![image](https://user-images.githubusercontent.com/1789116/97816529-f4138180-1ca6-11eb-8c7a-2e19639f3fa3.png)

**Comment by jlankitus** [comment]
hell yeah, thank you so much!
