### ISSUE TITLE
Does not work on Hololens 2

### ISSUE THREAD

**Issue by pavethem** [Iam1337/extOSC#14]
I wrote the same thing in the [forum thread](https://forum.unity.com/threads/released-extosc-open-sound-control.436159/page-4#post-6566710)
Basically the Hololens 2 does not seem to receive OSC messages and extOSC throws the same exception twice on startup (line 59 of OSCStandaloneManager)

Edit: The twice part is likely because I have two Receivers in my scene

**Comment by Iam1337** [comment]
Hi, It seems I was able to fix this error in commit 40c9051. Try now to build your project with a new version of extOSC.

**Comment by pavethem** [comment]
Thank you!
I will try it as soon as I can get my hands on the Hololens 2 again, which might be at the end of the week.

**Comment by pavethem** [comment]
I can confirm that this works now on the Hololens 2, so this issue can be closed. Thank you for your help!
There is quite a noticable delay however, but maybe that's just the way it is.
