### ISSUE TITLE
Errors when using through UPM

### ISSUE THREAD

**Issue by cwnuk-lfl** [Iam1337/extOSC#15]
When this package is included via UPM, these errors continually appear in the console:
```
Asset Packages/com.iam1337.extosc/CHANGELOG.md has no meta file, but it's in an immutable folder. The asset will be ignored.
Asset Packages/com.iam1337.extosc/LICENSE has no meta file, but it's in an immutable folder. The asset will be ignored.
Asset Packages/com.iam1337.extosc/README.md has no meta file, but it's in an immutable folder. The asset will be ignored.
```

This is on Unity 2019.4.12f1

**Comment by cwnuk-lfl** [comment]
It looks like those three files (Changelog, ReadMe, and License) are being added as part of your release process rather than in Unity.    It seems like one option might be to include those files or dummy versions of them within the repo's  Assets/extOSC directory, to then be overwritten by your release process?

**Comment by Iam1337** [comment]
Thanks, I added "dummy" files, maybe I'll do it better in the future.
