### ISSUE TITLE
OSCReceiver.LocalHost reads 0.0.0.0 while the script itself shows correct adress.

### ISSUE THREAD

**Issue by TheBricktop** [Iam1337/extOSC#17]
Is that a bug or naming missmatch?

**Comment by Iam1337** [comment]
If LocalHostMode is Any, then the OSC uses "0.0.0.0" and the script displays the first available local IP.

I thought it would be a handy function to quickly see available local address.

**Comment by TheBricktop** [comment]
So is there a way to get list od available local ips?

**Comment by TheBricktop** [comment]
Answer:
Okay so after some digging I've found that ip is recovered by OSCUtilities.GetLocalHost()
