### ISSUE TITLE
Sending string with utf-8 characters is not encoding right

### ISSUE THREAD

**Issue by TheBricktop** [Iam1337/extOSC#18]
When sending strings that contain utf-8 characters (Polish) im getting "?" on the output, where might be the culprit?
I think that there could be some encoding problem or special settings involved.

**Comment by Iam1337** [comment]
Hi, OSC protocol uses ASCII encoding for strings. extOSC has UTF-8 encoding for strings, just toggle option in top menu: _/Tools/extOSC/Settings/UTF-8_.

**Comment by TheBricktop** [comment]
OH. Yeez, thanks man You re awesome.
