### ISSUE TITLE
Receiver refuses to receive in 2018.2

### ISSUE THREAD

**Issue by TheBricktop** [Iam1337/extOSC#2]
Ive set up everything correct , all other osc monitors set to same port receive full packet of data, but unity is deaf, nothing coming from another computer in the same network (ip and port set correctly adresses mapped )

**Comment by Iam1337** [comment]
Have you disabled the firewall on your computer?

**Comment by TheBricktop** [comment]
Thing is Touchdesigner and processing can access data from ports without problems but this was my first bet, so ive made firewall exception for all instances of unity in public and private networking, but it didnt help.

**Comment by Iam1337** [comment]
Well, I'll add this to the future documentation.
