### ISSUE TITLE
string.Join error when importing

### ISSUE THREAD

**Issue by timFinn** [Iam1337/extOSC#23]
https://github.com/Iam1337/extOSC/blob/3b37fc27b5c45d9976a81e921dae96af32d8d69e/Assets/extOSC/Scripts/Editor/OSCDefinesManager.cs#L55

When importing, the following compiler error gets thrown. Using 2020.3.33f1

Library\PackageCache\com.iam1337.extosc@f76f5f953a\Scripts\Editor\OSCDefinesManager.cs(55,79): error CS1503: Argument 1: cannot convert from 'char' to 'string'

**Comment by timFinn** [comment]
https://github.com/Iam1337/extOSC/pull/24

**Comment by Iam1337** [comment]
Thanks! Sorry for late answer.
