### ISSUE TITLE
Window Debug bug

### ISSUE THREAD

**Issue by MrKamikazee** [Iam1337/extOSC#30]
Hi!, I got this bug while adjusting the windows and I don't know how to fix it.

![imagen_2023-09-29_195126489](https://github.com/Iam1337/extOSC/assets/64284557/fc4e986c-95a3-4809-94b8-d52d96754901)

**Comment by Iam1337** [comment]
What Unity version and OS you use?

**Comment by MrKamikazee** [comment]
I use Windows 11 and Unity 2022.3.3

**Comment by Iam1337** [comment]
extOSC from GitHub or Asset Store?

**Comment by MrKamikazee** [comment]
Sorry for the delay in getting back to you.
I just tried what you told me and it didn't work.
