### ISSUE TITLE
filtering on Console Window

### ISSUE THREAD

**Issue by sunriser111671** [Iam1337/extOSC#5]
This is a request to be able to address filter the Received/Transmitted entries on the OSC Console window. Adding a textbox for the Received and Transmitted tabs that only shows (or does not show with a toggle option) entries with addresses containing typed-in string in each respective entry list. Adding * before and after string may also help for prefix and suffix wildcard matches.

**Comment by Iam1337** [comment]
Yes, I plan to add this feature in future updates. The filter will look like a mask: _"/lights/*/value"_

**Comment by Iam1337** [comment]
Requested functionality added in https://github.com/Iam1337/extOSC/commit/a156838f45ce9c25e78c869a1a4634277229cba7 commit.
