### ISSUE TITLE
extOSC works mostly, but on android it has its hiccups

### ISSUE THREAD

**Issue by TheBricktop** [Iam1337/extOSC#8]
Currently im trying to push a single texture using osc from pc to android, and it works. but it seems like it doesnt like broadcasting a large string, maybe it would be better to use a bytearray and sling it in a blob but i dont have time now. 
Worse thing is that while im trying to do the same from android to pc, it doesnt seem to work at all while code is identical.
Is there a special setting to be set for android to transmit data? 
OSChook sends data without a hiccup.

**Comment by Iam1337** [comment]
Hi, maximum message size in extOSC is 65507 (including the header), try increasing the packet size in file OSCConverter.cs:15:
`private static int _packetSize = 65507;`

If this does not help, throw me the logs from Unity. (ext@iron-wall.org)

**Comment by fchen09** [comment]
@Iam1337 @TheBricktop 
Hi, I got the same hiccups on Samsung Note 10+ with Android 12. I tried setting the maximum message size to 655070, but the hiccups remain. Have you guys solved the bug? Could you share it? Thanks!
