### ISSUE TITLE
Error when creating new UI element in Unity 2019.2.8f1

### ISSUE THREAD

**Issue by diedetap** [Iam1337/extOSC#9]
Hi there,

When I try to add a new UI element (pad, slider, button etc) I get the following error:

`TargetParameterCountException: Number of parameters specified does not match the expected number.`

I'm currently running Unity 2019.2.8f1, the issue is also present in a clean Unity project with only extOSC added. Any help would be much appreciated!

**Comment by Iam1337** [comment]
Fixed in last commit.
